name: Project Tests

on:
  push:
    branches:
      - main

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "*.py"
