name: Project Tests

on:
  push:
    branches:
      - main

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Give permissions
        run: chmod +x ./main/project/tests.sh
      - name: run tests
        run: |
          cd main
          ./project/tests.sh